title: Plain Lang
description: A guide for plain language technical writing. 
theme: just-the-docs

url: https://karlwasson.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
